name: CICD

on:
 workflow_dispatch: 
     inputs:
         environment:
             description: This is where the workflow will run
             required: true
             type: choice
             options:
                 - dev
                 - prod
                 - staging
               
jobs:  

    code:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              run: echo "Code Clone from GIT"
    build:
        needs: code
        runs-on: ubuntu-latest
        steps:
            - name: Build Code
              run: echo "Building Code"
    test:
        needs: [code,build]
        runs-on: ubuntu-latest
        steps:
            - name: Test the Code
              run: echo "Testing Code"
    deploy:
        if: ${{ inputs.environment == 'dev' }}
        needs: [build,test]
        runs-on: ubuntu-latest
        steps:
            - name: Deploy the Code
              run: echo "Deploying Code"
