name: Hello

on: 
 push:
    branches: [main]
jobs:
    
    greet:
     runs-on: ubuntu-latest
     steps: 
         - name: say hello to user
           run: echo "Hello All"

         - name: say hello to username
           run:  echo "Hello $USER"

    details:
        runs-on: ubuntu-latest
        steps:
         - name: Display Docker & Python version
         - run: docker --version && python --version
         
           
